version: "3.3"

services:
  go-opera:
    build: .
    restart: always
    container_name: "go-opera"
    volumes:
      - ./volumes/opera:/data
    command: --genesis /data/mainnet.g --datadir /data --nat extip:1.1.1.1 --nousb --http --http.addr "0.0.0.0" --http.vhosts="*" --http.corsdomain="*" --ws --ws.addr "0.0.0.0" --ws.origins="*" --http.api="ftm,eth,debug,admin,web3,personal,net,txpool,sfc"
    ports:
      - "5050:5050"
      - "18545:18545"
      - "18546:18546"
      - "18547:18547"
      - "19090:19090"
